function startQuiz(config){
  const root=document.getElementById('quizApp');let order=[...config.questions.keys()];let at=0,correct=0,checked=false;
  for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render(){checked=false;const q=config.questions[order[at]];const hint=q.hint?`<details class="grammar-hint"><summary>Grammar hint</summary><p>${esc(q.hint)}</p></details>`:'';const translation=q.translation?`<details class="grammar-hint translation-hint"><summary>Translation</summary><p>${esc(q.translation)}</p></details>`:'';root.innerHTML=`<div class="progress"><span>Question ${at+1} of ${order.length}</span><span>${correct} correct</span></div><div class="bar"><span style="width:${at/order.length*100}%"></span></div><p class="prompt">${q.prompt}</p>${translation}${hint}<p class="context">${esc(q.context||'Choose the best answer.')}</p><form id="answerForm"><div class="options">${q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}"><span>${esc(o)}</span></label>`).join('')}</div><div class="actions"><button class="primary" type="submit">Check answer</button><button type="button" id="next" disabled>${at===order.length-1?'See results':'Next question'}</button></div></form><div id="feedback" aria-live="polite"></div><div id="answerChart"></div>`;
    root.querySelector('#answerForm').addEventListener('submit',check);root.querySelector('#next').addEventListener('click',next);
  }
  function check(e){e.preventDefault();if(checked)return;const q=config.questions[order[at]],chosen=root.querySelector('input[name="answer"]:checked');if(!chosen){root.querySelector('#feedback').innerHTML='<div class="feedback bad">Choose an answer first.</div>';return}checked=true;const n=Number(chosen.value),ok=n===q.answer;if(ok)correct++;root.querySelectorAll('.option').forEach((el,i)=>{if(i===q.answer)el.classList.add('correct');else if(i===n)el.classList.add('wrong');el.querySelector('input').disabled=true});root.querySelector('#feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}">${ok?'Correct!':'Not quite. The answer is '+esc(q.options[q.answer])+'.'}<span class="explain">${esc(q.explanation)}</span></div>`;if(q.conjugation){const people=['io','tu','lui/lei','noi','voi','loro'];const rows=people.map((person,i)=>`<div class="chart-row${i===q.conjugation.correctIndex?' chart-correct':''}"><span>${person}</span><strong>${esc(q.conjugation.forms[i])}</strong></div>`);root.querySelector('#answerChart').innerHTML=`<section class="answer-chart"><h3>${esc(q.conjugation.title)}</h3><div class="chart-grid"><div>${rows.slice(0,3).join('')}</div><div>${rows.slice(3).join('')}</div></div></section>`}root.querySelector('button[type="submit"]').disabled=true;root.querySelector('#next').disabled=false;
  }
  function next(){if(at<order.length-1){at++;render()}else finish()}
  function finish(){root.innerHTML=`<div class="complete"><strong>${correct}/${order.length}</strong><h2>Quiz complete</h2><p>${correct===order.length?'Perfetto! You answered every question correctly.':'Review the explanations, then try again to strengthen the patterns.'}</p><div class="actions" style="justify-content:center"><button class="primary" id="again">Try again</button><a class="back" style="padding:10px" href="index.html">All quizzes</a></div></div>`;root.querySelector('#again').onclick=()=>{at=0;correct=0;order.sort(()=>Math.random()-.5);render()}}
  render();
}
